name: mage-infra
services:
  web:
    image: mageai/mageai:latest
    command: sh -c "/app/run_app.sh mage start projects --instance-type web_server" 
    ports:
      - 6789:6789
    volumes:
      - ../mage_code:/home/src
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MAGE_DATABASE_CONNECTION_URL: "postgresql+psycopg2://${POSTGRES_USER:-mageuser}:${POSTGRES_PASSWORD:-magepassword}@db:5432/${POSTGRES_DB:-magedb}"
      REDIS_URL: redis://redis:6379/0
      ULIMIT_NO_FILE: 8192
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://127.0.0.1:6789/", "||", "exit", "1"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
  scheduler:
    image: mageai/mageai:latest
    command: sh -c "/app/run_app.sh mage start projects --instance-type scheduler"
    volumes:
      - ../mage_code:/home/src
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started 
    environment:
      MAGE_DATABASE_CONNECTION_URL: "postgresql+psycopg2://${POSTGRES_USER:-mageuser}:${POSTGRES_PASSWORD:-magepassword}@db:5432/${POSTGRES_DB:-magedb}"
      REDIS_URL: redis://redis:6379/0
      ULIMIT_NO_FILE: 8192
  db:
    image: postgres:13-alpine3.17
    volumes:
      - ../pg_data:/data/postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-mageuser}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-magepassword}"
      POSTGRES_DB: "${POSTGRES_DB:-magedb}"
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER:-mageuser} -d ${POSTGRES_DB:-magedb}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

